### ISSUE TITLE
install script not working on 8.1.3

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [bjwelker/Snapcast-piCore#1]
Hi @bjwelker 
I just tried to set this up on a fres piCore installation.
At first I tried to use the latest piCore version (8.1.3) but that didn't work.

I didn't try to find out what is exactly not working but I figured that your script might only work with the current version of the time you made it, and that was 7.0.

So I installed it again on a fresh piCore 7.0 and all is good.

Maybe you could link to the 7.0 version download in your readme for now.

**Comment by tuxuser** [comment]
Fixed with commit b61e3ed

**Comment by tuxuser** [comment]
@bjwelker Is it possible to merge the PR?

**Comment by bjwelker** [comment]
done!
